---
- hosts: myhost
  remote_user: root 

  tasks: 
  - name: install httpd package 
    yum: name=httpd
    tags: inshttpd
  - name: copy conf file
    copy: src=/root/httpd.conf dest=/etc/httpd/conf backup=yes 
    notify: restart service
  - name: start service
    service: name=httpd state=started enabled=yes
    tags: rehttpd

  handlers: 
  - name: restart service 
    service: name=httpd state=restarted
