---
- hosts: myhost
  remote_user: root 

  tasks: 
  - name: create some file
    file: name=/data{{ item }} state=touch 
    when: ansible_distribution_major_version=="7"
    with_items: 
    - file1
    - file2 
    - file3

  - name: install some package 
    yum: 
      name: ['sl', 'htop', 'hping3']
